apiVersion: v1
kind: ReplicationController
metadata:
  name: mesos-agent
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mesos-agent
    spec:
      containers:
      - name: mesos-agent
        image: linkerrepository/mesos-slave:0.28.1
        command: ["mesos-slave"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 5051
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /sys/fs/cgroup
          name: cgroup
        env:
        - name: MESOS_PORT
          value: "5051"
        - name: MESOS_CONTAINERIZERS
          value: "docker"
        - name: MESOS_MASTER
          value: zk://zookeeper:2181/mesos
        - name: MESOS_QUORUM
          value: "1"
        - name: MESOS_LOG_DIR
          value: /var/log/mesos
        - name: MESOS_WORK_DIR
          value: /var/tmp/mesos
      volumes:
      - name: docker-sock
        hostPath: 
          path: /var/run/docker.sock
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup

