apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: z1
    port: 2181
  - name: z2
    port: 2888
  - name: z3 
    port: 3888
  selector:
    app: zookeeper
